//
//  TipsModel.swift
//  FashionTips
//
//  Created by Natalie Lim on 7/6/16.
//  Copyright © 2016 Natalie Lim. All rights reserved.
//

import GameKit

struct HacksModel {
    let hacks = [
        "Eating bananas is a natural cure to reduce the effects of stress and anxiety",
        "Want softer and more beautiful skin? Add rose water and coconut oil to your warm bath. Soak for 20 minutes and rinse. You won’t regret it!",
        "Struggling to grasp a concept at school/work? Try Googling the subject with ‘site:.edu’ and ‘type:.ppt’. This will give you powerpoint presentations on the given subject from universities.",
        "Just 20 minutes of exercise for three days a week will increase your endorphins (and therefore your happiness) by around 10-20%.",
        "Roughly 20,000 pennies from the year 1955 were stuck with doubled obverse lettering. They are now worth up to $20,000 USD each!",
        "Sitting on a medicine ball instead of a chair while doing work can improve your focus and productivity by 50%.",
        "When you want to cross words out that you don’t want to be legible, instead of scribbling over them, write random letters over the original.",
        "You can use a rubber band to keep a door from latching, by looping over a doorknob, twisting to form an ‘X’ over the latch, and looping around the opposite doorknob",
        "Does your dorm smell bad? Tape a dryer sheet over the AC unit and turn it on.",
        "For people who use their phone to watch things often and are tired of leaning it onto something where it will fall down after awhile: Use your sunglasses!",
        "When ironing a button-up shirt, flip it inside-out to easily iron over the button side.",
        "Put old newspaper at the bottom of your trash bin to absorb food juices.",
        "To remove the stem from strawberries, use a straw. (poke the straw through the center of the strawberry)",
        "To make BLT’s or any toasted sandwich, place 2 slices of bread in a single toaster slot. This way, the bread gets warm and toasty on the outside, but stays soft and chewy on the inside.",
        "Take an old CD spindle and turn it into a bagel tote.",
        "Take pictures of friends holding items you’ve lent them with your iPhone, so you will remember down the road.",
        "Place a rubberband around an open paint can to wipe your brush on, and keep paint off the side of the can.",
        "Use a can opener to open blister packs and avoid cutting yourself.",
        "Hair straighteners = mini irons",
        "A frozen, saturated sponge in a bag makes an icepack that won’t drip all over when it melts.",
        "Use a bread tab/clip or paper clip to hold your spot on a roll of tape.",
        "Clear up hazy car headlights with toothpaste.",
        "Cut open toilet paper rolls and use it as a cuff to save your wrapping paper and keep it from unrolling.",
        "When heating leftovers, space out a circle in the middle, it will heat up much more evenly.",
        "Chew gum when chopping onions to avoid those tearing up.",
        "Rub a walnut on damaged wooden furniture to cover up dings.",
        "Tie a small piece of bright-colored fabric to your luggage. This saves a lot of time to check if it’s your bag or not.",
        "‘Mount’ your phone to the seat in front of you using a zip lock bag.",
        "Turn an old milk jug into a watering can by poking holes in the lid.",
        "Keep tall boots upright by putting in wine bottles or pool noodles.",
        "Need to clean your microwave? Fill a bowl with water and microwave it for 2-3 minutes. The steam will loosen any dried food particles for easy cleaning.",
        
        "Pay for things using cash so it’s not ‘imaginary’ money. You’re much less likely to waste it.",
        "If you spend a while looking for something, after you find and use it, put it back in the first place you looked for it.",
        "If you have brain freeze, press the underside of your tongue against the roof of your mouth.",
        "Put your alarm clock at the far side of your room rather than next to your bed in order to get out of bed faster.",
        "To chill a drink, wrap a wet towel around your beverage and put it in the freezer. In about fifteen minutes it will be almost completely ice cold.",
        "Use a clothespin to hold a nail while you are hammering to avoid smashing your fingers.",
        "Use a staple remover to save your fingernails when trying to add things to your key ring.",
        "Place Otter pops upright before freezing to guarantee a clean cut.",
        "Fill plastic water bottles a quarter of the way full and lay on the sides and put into freezer. This way when frozen you can fill with water and have ice cold water on the go.",
        "Toward the end of your shower, use colder water to wash yourself. This will refresh you and get blood flowing. Further, it also closes your pores, which will prevent more dirt and bacteria from seeping into your skin and will help with acne issues.",
        "Turn a cord into a coil cord by wrapping it around a pen, then going over it with a hairdryer for 2-3 minutes.",
        "To peel an orange easier, gently roll the orange around to loosen the peel from the fruit. This will make it easier to remove the peel.",
        "Tap the side of a soda can to get rid of the fizz so the carbonated liquid doesn't erupt when you open the can.",
        "Pour soda along the side of the cup and not directly into it. This conserves the carbonation of the soda.",
        "If you have to store cookies and pastries in a container, leave bread in the container, and it will keep the baked goods moist.",
        "Water damaged phone? Tape over the charging port and headphone jack hole (to make sure rice doesn’t get inside) and put in a ziploc bag with rice for 24 hours. It should absorb the moisture and work again!",
        "Amplify your music or alarm by putting it in a glass.",
        "Seal plastic bags with aluminum foil and an iron. Fold the aluminum foil around the opened end of the bag and iron over.",
        "If you have trouble removing any kind of stuck on sticker, label, decal, or adhesive tape from any surface try heating it up with a blow dryer for an easier removal.",
        "Store ready to blend healthy smoothie packs in zip-lock bags in your freezer for a fast and easy snack.",
        "Prep to lose weight by spending a couple of hours 2 nights a week preparing healthy, pre-portioned meals in containers for the next few days. This way, when you’re hungry, it’ll be easy to reach for one rather letting your hunger impulses take over.",
        "Put your phone on airplane mode to stop ads while playing games on your phone.",
        "If you need emergency lighting and don’t have candles, put crayons in a class cup or plate and light. They will burn for hours.",
        "You can heal paper cuts and immediately stop the pain by putting chapstick on them ",
        "Cut tons of tomatoes or grapes at once by laying them on a small plate. Place another plate on top and then run a very sharp knife through the gap between the two plates. Holding the top plate securely with your other hand. Voila!",
        "An easy way to peel garlic cloves - put them in a hard, enclosed container for about 15 seconds, the cloves will be skin-free.",
        "It is actually easier to spread jelly or cream cheese with the back of a spoon. Try it!",
        "To increase the range of your car key fobs unlocking signal, hold it against your cheek before you click the button.",
        "The best way to keep your windshield free of fog? Run the air conditioner.",
        "Take a picture of your luggage so you’ll have something to show people if it gets lost. This also works for parking spots and coat check tickets.",
        "Take a picture of your kids when you get to a place or even with a large crowd. That way, if you get separated, you can show security what they’re wearing.",
        "Pick your outfit out the night before to save time in the morning.",
        "Take a pen spring from an old pen and wrap it around your charger cord. This will protect it from breaking and bending.",
        "When writing an email, leave the recipient email field blank until you're ready to send it. This prevents accidental emails.",
        "If keys look too similar to you, paint the tops with different colored nail polish so you can tell them apart.",
        "Dig a hole in your leftovers when heating them up in the microwave so the heat will spread evenly.",
        "Press a hot spoon to a mosquito bite to stop the itching. The heat will destroy the protein that is causing the itching.",
        "Get the WiFi passwords at various places by checking the comments section of their FourSquare accounts.",
        "If you're sitting outside and enjoying the fresh air but not the mosquitoes, then point a fan at yourself to prevent mosquitoes from coming at you. These insects are weak fliers, so they won't be able to navigate the winds to land on your skin.",
        "The first thing you should say when you call 911 is ‘I need [service] at [address]. Again, that's [address].’ Your operator can have the right people dispatched while you are sharing more details of your story.",
        "Carry a box and a bin with you as you clean. A bin can be a trash bag or any other container. Stuff things to be trashed in the bin and things that belong in another room in the box. As you move from room to room, put the items from the box back in their rightful places.",
        "When someone is treating you but you don't know what their price range is, then ask them what they are thinking of ordering or what they recommend.",
        "Whenever you buy a product, go to the manufacturer's site and upload the digital version of the manual onto Google Drive or Dropbox, and you'll never have to keep paper copies again.",
        "Instead of reaching deep into a microwaveable popcorn bag, enjoy the treat by ripping a square into the side of the bag and creating your own resourceful bowl.",
        "Finding the end of masking tape can be such an annoying task. To soften up old masking tape, simply plop it in the microwave and warm it up for a few seconds.",
        "Cover up scratches on your car by using a matching color of nail polish.",
        "Clean out a lotion bottle to store your phone and other essentials inside of it. It'll keep the sand from getting into and scratching the surface of your phone too!",
        "Wrapping your glassware in newspaper takes forever. Ain't nobody got time for that! Instead, stack your plates on top of disposable foam plates to keep them safe and unbroken during a move.",
        "Use the spacebar to scroll down a page. Hold the shift key and the space bar at the same time to scroll back up again.",
        "Hit the call button of your phone to redial the last person you spoke to. No need to go into your contacts.",
        "Use Google as a dictionary by typing 'define' followed with the word you want to understand. You can also use it as an FAA database for flight details.",
        "To highlight a word, don’t drag across it with the mouse. Double click it. And don’t bother deleting text; just type.",
        "Avoid shutter lag by half pressing down the button of your camera before you take a picture. For folks who still use cameras.",
        "Pour coffee into an ice tray, so you make coffee-flavored cubes that don’t water down your iced coffee.",
        "Spills are never fun. To keep unwanted spillage from happening, cover the lip of bottles with plastic wrap. Then seal with the lid.",
        "Lay out all your credit / bank cards from your wallet on a copy machine and email yourself scans of the front and back. That way you have all the card numbers and the 800 numbers for customer service. If your wallet gets stolen (especially when on the road) you have quick access and a way to remember which cards to cancel.",
        "This seems redundant, but taking a photo of what your electronics looked like all plugged in beforehand can save you a lot of time when setting things up after moving to a new apartment.",
        "Crack an egg on a flat surface, not on the side of a bowl. This minimizes the likelihood of pieces of shell getting into your egg.",
        "Here’s a great one for removing oil stains from anything (including the leather seats of your parents’ car…) - generously cover the stained area with flour or cornstarch.  Let it sit for a while and it will miraculously soak up your oil stains.",
        "Stop using spoons for your coffee. Simply add your stuff (sugar, milk, rum, what-have-you) to your empty coffee mug, then pour your coffee in. It mixes just as well, and you don’t have a dirty spoon left over.",
        "If you have kids, you know two things: 1) they fill reams of paper with 'artwork;' and 2) you will be going to a lot of birthday parties. Use their 'masterpieces' to wrap presents; it saves money and it’s more personalized.",
        "You can use a piece of dry spaghetti to light candles that have burned down inside their holder.",
        "Every time you use up a household necessity (box of spaghetti, carton of milk, bag of chocolate chips), take a photo of the empty package with your mobile phone. When you’re in the store, just review your photos to see what you need. Delete the photos as you add things to your shopping cart.",
        "Honey and olive oil make a cheap face mask. The acid in the honey removes dead skin cells and brightens. Olive oil moisturizes.",
        "To get the built up residue off of your showerhead, tie a bag of vinegar around the shower head, leave it there overnight, and it will clean everything off with no work.",
        "Put a stocking over the end of a vacuum to find tiny items like earrings.",
        "Doritos are great for kindling if you can’t find any.",
        "Use a muffin tin to serve condiments at a BBQ. (it will also help you cut down on dish washing)",
        "Put a wooden spoon across a boiling pot of water to keep it from boiling over.",
        "Turn on your seat warmer to keep pizza hot while driving home.",
        "Need an inexpensive cookbook holder? Try a pants hanger.",
        "Put pancake mix in a ketchup bottle for a no-mess experience.",
        "Use unscented dental floss to cut cakes, cheeses and other soft solids perfectly",
        "Hide emergency money in an empty chapstick. (this is very helpful on vacation!)",
        "If you’re at a hotel and run out of chargers, the back of a TV usually has a USB plugin.",
        "If you need to pee or smoke at a bar, placing your coaster on top of your drink is universal bar language for ‘I’m coming back.’ Prevents you from losing your drink and seat.",
        "Need a flathead screwdriver? Basic power plugs usually fit medium and large-sized screws.",
        "Drill holes in the bottom of your garbage can to make putting in and taking out bags much easier -- no suction issues.",
        "Use your cellphone light underneath a water bottle to make a lantern that distributes light better than the direct beam.",
        "To stop receiving marketing emails, filter by the word ‘unsubscribe’.",
        "Use an accented letter as your passcode. No one will ever be able to guess it.",
        "Want to take a quick nap on transit but afraid of your bag getting stolen -- loop your foot through your bag strap.",
        "Put a squeeze-ketchup bottle top over your vacuum nozzle to easily clean your keyboard, phone microphone or other small nook on an electronic device.",
        "Keep your cat (or dog) from unrolling toilet paper by pushing the end into the toilet paper roll",
        "Do something unusual when locking the door before a long trip to remember that you’ve definitely done it.",
        "Paint the bottom of the sliding glass door lock white to see if it’s locked from afar.",
        "Use a strong magnet to find nails and studs in your wall.",
        "Turn an empty six-pack into an outdoor dining kit. (you can put in plastic utensils, napkins, salt and pepper, etc.",
        "If you ever need to stop and ask directions, skip the gas station and find a pizza delivery place.",
        "When moving, pack heavy items, like books, in a rolling suitcase. Boxes are hard to carry and tend to tear when they’re too heavy",
        "Bake cupcakes directly in ice-cream cones. It’s so much easier and more fun for kids to eat!",
        "A comb makes a perfect nail holder",
        "Facial cleansing wipes do an amazing job of getting mud off of nice shoes."]

    
    func getRandomHack() -> String {
        let randomNumber = GKRandomSource.sharedRandom().nextIntWithUpperBound(hacks.count)
        
        return hacks[randomNumber]
    }
}

